name: Database Migrations

on:
  push:
    branches: [main, staging]
    paths:
      - 'packages/database/drizzle/**'
      - 'packages/database/src/schema-types/**'
      - 'packages/database/drizzle.config.ts'
      - '.github/workflows/database-migrations.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run migrations against'
        required: true
        type: choice
        options:
          - main
          - staging
        default: staging

# Only one migration per environment at a time
concurrency:
  group: db-migrate-${{ github.ref }}
  cancel-in-progress: false  # Never cancel migrations

jobs:
  migrate:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: ./.github/actions/setup-node-env
        with:
          use-stickydisk: 'false'

      - name: Run migrations
        run: pnpm run db:migrate
        env:
          DATABASE_URL: ${{ secrets.DB_URL }}
          NODE_TLS_REJECT_UNAUTHORIZED: '0'