include:
  - supabase/docker-compose.yml

services:
  redis:
    image: redis
    container_name: buster-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  api:
    build: ./api
    env_file:
      - .env
    ports:
      - "3001:3001"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      
  web:
    build: ./web
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api

volumes:
  db_data: 