packages:
  - packages/*
  - apps/server
  - apps/momentic
  - apps/electric-server
  - apps/trigger
  - apps/api
  - apps/cli
  - apps/web
  - apps/supabase

catalog:
  '@aws-sdk/client-s3': ^3.922.0
  '@aws-sdk/s3-request-presigner': ^3.922.0
  '@electric-sql/client': ^1.1.1
  '@electric-sql/react': ^1.0.16
  '@supabase/supabase-js': 2.78.0
  '@trigger.dev/build': ^4.0.5
  '@trigger.dev/sdk': ^4.0.5
  '@types/js-yaml': 4.0.9
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  ai: ^5.0.86
  axios: ^1.13.1
  dayjs: ^1.11.18
  dotenv: ^17.2.3
  drizzle-orm: ^0.44.7
  hono: ^4.10.4
  js-yaml: 4.1.0
  lodash-es: ^4.17.21
  pg: ^8.16.3
  react: ^19.2.0
  react-dom: ^19.2.0
  tsup: ^8.5.0
  tsx: ^4.20.6
  uuid: ^13.0.0
  vite: ^7.1.12
  vite-tsconfig-paths: 6.0.0-beta.4
  vitest: ^4.0.6
  zod: ^3.25.0

minimumReleaseAge: 0
