packages:
  # Core packages
  - 'packages/*'
  
  # Applications
  - 'apps/web'
  - 'apps/server' 

catalog:
  uuid: "^11.0.0"
  zod: "^3.0.0"
  ai: "^4.0.0"
  '@trigger.dev/sdk': "^3.0.0"
  '@supabase/supabase-js': "^2.50.0"
