packages:
  # Core packages
  - "packages/*"

  # Applications
  - "apps/web"
  - "apps/server"
  - "apps/electric-server"
  - "apps/trigger"
  - "apps/api"

catalog:
  "@mastra/core": "^0.10.8"
  "@supabase/supabase-js": "^2.50.0"
  "@trigger.dev/build": "^4.0.0-v4-beta.24"
  "@trigger.dev/sdk": "^4.0.0-v4-beta.24"
  ai: "^4.0.0"
  axios: "^1.11.0"
  "braintrust": "^0.0.209"
  dotenv: "^17.2.0"
  drizzle-orm: "^0.44.2"
  hono: "^4.8.0"
  pg: "^8.16.2"
  tsup: "^8.5.0"
  tsx: "^4.20.0"
  uuid: "^11.0.0"
  vite: "6.3.5"
  "vite-tsconfig-paths": "^5.1.4"
  vitest: "3.2.4"
  zod: "^3.25.0"
