export const loadHeavyEditorKits = async () => {
  const [
    ai,
    blockMenu,
    codeBlock,
    table,
    toggle,
    toc,
    media,
    callout,
    column,
    math,
    date,
    mention,
    font,
    discussion,
    comment,
    suggestion,
    slash,
    autoformat,
    cursorOverlay,
    dnd,
    emoji,
    docx,
    markdown,
    blockPlaceholder,
    floatingToolbar,
    busterStream
  ] = await Promise.all([
    import('./plugins/ai-kit'),
    import('./plugins/block-menu-kit'),
    import('./plugins/code-block-kit'),
    import('./plugins/table-kit'),
    import('./plugins/toggle-kit'),
    import('./plugins/toc-kit'),
    import('./plugins/media-kit'),
    import('./plugins/callout-kit'),
    import('./plugins/column-kit'),
    import('./plugins/math-kit'),
    import('./plugins/date-kit'),
    import('./plugins/mention-kit'),
    import('./plugins/font-kit'),
    import('./plugins/discussion-kit'),
    import('./plugins/comment-kit'),
    import('./plugins/suggestion-kit'),
    import('./plugins/slash-kit'),
    import('./plugins/autoformat-kit'),
    import('./plugins/cursor-overlay-kit'),
    import('./plugins/dnd-kit'),
    import('./plugins/emoji-kit'),
    import('./plugins/docx-kit'),
    import('./plugins/markdown-kit'),
    import('./plugins/block-placeholder-kit'),
    import('./plugins/floating-toolbar-kit'),
    import('./plugins/buster-stream-kit').catch(() => ({ BusterStreamKit: [] as any[] }))
  ]);

  const kits = [
    ...(ai.AIKit || []),
    ...(blockMenu.BlockMenuKit || []),
    ...(codeBlock.CodeBlockKit || []),
    ...(table.TableKit || []),
    ...(toggle.ToggleKit || []),
    ...(toc.TocKit || []),
    ...(media.MediaKit || []),
    ...(callout.CalloutKit || []),
    ...(column.ColumnKit || []),
    ...(math.MathKit || []),
    ...(date.DateKit || []),
    ...(mention.MentionKit || []),
    ...(font.FontKit || []),
    ...(discussion.DiscussionKit || []),
    ...(comment.CommentKit || []),
    ...(suggestion.SuggestionKit || []),
    ...(slash.SlashKit || []),
    ...(autoformat.AutoformatKit || []),
    ...(cursorOverlay.CursorOverlayKit || []),
    ...(dnd.DndKit || []),
    ...(emoji.EmojiKit || []),
    ...(docx.DocxKit || []),
    ...(markdown.MarkdownKit || []),
    ...(blockPlaceholder.BlockPlaceholderKit || []),
    ...(floatingToolbar.FloatingToolbarKit || []),
    ...((busterStream as any).BusterStreamKit || [])
  ];

  return kits;
};
