/**
 * Secret keys used by the @buster/data-source package
 * These are primarily for integration testing against various databases
 */

export const DATA_SOURCE_KEYS = {
  // R2 Default Storage Credentials
  R2_ACCOUNT_ID: 'R2_ACCOUNT_ID',
  R2_ACCESS_KEY_ID: 'R2_ACCESS_KEY_ID',
  R2_SECRET_ACCESS_KEY: 'R2_SECRET_ACCESS_KEY',
  R2_BUCKET: 'R2_BUCKET',

  // PostgreSQL Test Credentials
  TEST_POSTGRES_HOST: 'TEST_POSTGRES_HOST',
  TEST_POSTGRES_DATABASE: 'TEST_POSTGRES_DATABASE',
  TEST_POSTGRES_USERNAME: 'TEST_POSTGRES_USERNAME',
  TEST_POSTGRES_PASSWORD: 'TEST_POSTGRES_PASSWORD',
  TEST_POSTGRES_PORT: 'TEST_POSTGRES_PORT',
  TEST_POSTGRES_SSL: 'TEST_POSTGRES_SSL',

  // MySQL Test Credentials
  TEST_MYSQL_HOST: 'TEST_MYSQL_HOST',
  TEST_MYSQL_DATABASE: 'TEST_MYSQL_DATABASE',
  TEST_MYSQL_USERNAME: 'TEST_MYSQL_USERNAME',
  TEST_MYSQL_PASSWORD: 'TEST_MYSQL_PASSWORD',

  // Snowflake Test Credentials
  TEST_SNOWFLAKE_ACCOUNT_ID: 'TEST_SNOWFLAKE_ACCOUNT_ID',
  TEST_SNOWFLAKE_WAREHOUSE_ID: 'TEST_SNOWFLAKE_WAREHOUSE_ID',
  TEST_SNOWFLAKE_USERNAME: 'TEST_SNOWFLAKE_USERNAME',
  TEST_SNOWFLAKE_PASSWORD: 'TEST_SNOWFLAKE_PASSWORD',
  TEST_SNOWFLAKE_DATABASE: 'TEST_SNOWFLAKE_DATABASE',

  // BigQuery Test Credentials
  TEST_BIGQUERY_PROJECT_ID: 'TEST_BIGQUERY_PROJECT_ID',
  TEST_BIGQUERY_SERVICE_ACCOUNT_KEY: 'TEST_BIGQUERY_SERVICE_ACCOUNT_KEY',

  // SQL Server Test Credentials
  TEST_SQLSERVER_SERVER: 'TEST_SQLSERVER_SERVER',
  TEST_SQLSERVER_DATABASE: 'TEST_SQLSERVER_DATABASE',
  TEST_SQLSERVER_USERNAME: 'TEST_SQLSERVER_USERNAME',
  TEST_SQLSERVER_PASSWORD: 'TEST_SQLSERVER_PASSWORD',

  // Redshift Test Credentials
  TEST_REDSHIFT_HOST: 'TEST_REDSHIFT_HOST',
  TEST_REDSHIFT_DATABASE: 'TEST_REDSHIFT_DATABASE',
  TEST_REDSHIFT_USERNAME: 'TEST_REDSHIFT_USERNAME',
  TEST_REDSHIFT_PASSWORD: 'TEST_REDSHIFT_PASSWORD',

  // Databricks Test Credentials
  TEST_DATABRICKS_SERVER_HOSTNAME: 'TEST_DATABRICKS_SERVER_HOSTNAME',
  TEST_DATABRICKS_HTTP_PATH: 'TEST_DATABRICKS_HTTP_PATH',
  TEST_DATABRICKS_ACCESS_TOKEN: 'TEST_DATABRICKS_ACCESS_TOKEN',
} as const;

export type DataSourceKeys = (typeof DATA_SOURCE_KEYS)[keyof typeof DATA_SOURCE_KEYS];
