/**
 * Secret keys used by the @buster/slack package
 */

export const SLACK_KEYS = {
  // OAuth Credentials
  SLACK_CLIENT_ID: 'SLACK_CLIENT_ID',
  SLACK_CLIENT_SECRET: 'SLACK_CLIENT_SECRET',
  SLACK_SIGNING_SECRET: 'SLACK_SIGNING_SECRET',
  SLACK_REDIRECT_URI: 'SLACK_REDIRECT_URI',

  // Bot Token (for testing)
  SLACK_BOT_TOKEN: 'SLACK_BOT_TOKEN',

  // Test Configuration
  SLACK_CHANNEL_ID: 'SLACK_CHANNEL_ID',
  SLACK_TEST_JOIN_CHANNEL_ID: 'SLACK_TEST_JOIN_CHANNEL_ID',
  SLACK_TEST_LEAVE_CHANNEL_ID: 'SLACK_TEST_LEAVE_CHANNEL_ID',
  SLACK_TEST_ACCESS_TOKEN: 'SLACK_TEST_ACCESS_TOKEN',

  // Test Control Flags
  SLACK_SKIP_DELETE_TESTS: 'SLACK_SKIP_DELETE_TESTS',
  SLACK_SKIP_LEAVE_TESTS: 'SLACK_SKIP_LEAVE_TESTS',

  // App Configuration
  SLACK_APP_SUPPORT_URL: 'SLACK_APP_SUPPORT_URL',
} as const;

export type SlackKeys = (typeof SLACK_KEYS)[keyof typeof SLACK_KEYS];
