ALTER TABLE "api_keys" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "asset_permissions" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "asset_search" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "collections" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "collections_to_assets" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "dashboard_versions" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "dashboards" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "data_sources" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "dataset_columns" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "datasets" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "messages_deprecated" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "organizations" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "permission_groups" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "permission_groups_to_identities" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "teams" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "teams_to_users" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "terms" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "terms_to_datasets" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "threads_deprecated" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "threads_to_dashboards" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "user_favorites" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "users" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "users_to_organizations" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE "terms_search" CASCADE;