name: buster
include:
  - "**/*.test.yaml"
  - "**/*.module.yaml"
parallel: 5
environments:
  - name: development
    baseUrl: http://localhost:3000
    envVariables:
      EMAIL: "chad@buster.so"
      PASSWORD: "password"
      SUPABASE_URL: "http://localhost:54321/auth/v1/token?grant_type=password"
      SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"
ai:
  agentConfig:
    locator: v2
    assertion: v2
    visual-assertion: v2
    text-extraction: v2
  aiFailureAnalysis: true
  aiAction: true
