name: Biome Lint Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.json'
      - 'biome.json'
      - '.github/workflows/biome-lint.yml'

jobs:
  biome-lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
          
      - name: Run Biome lint check
        run: npm run check
        
      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules/
          retention-days: 1

  build-database:
    runs-on: ubuntu-latest
    needs: biome-lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
          
      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules/
        
      - name: Build database package
        run: npm run build
        working-directory: packages/database

  build-access-controls:
    runs-on: ubuntu-latest
    needs: [biome-lint, build-database]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
          
      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules/
        
      - name: Build access-controls package
        run: npm run build
        working-directory: packages/access-controls

  build-data-source:
    runs-on: ubuntu-latest
    needs: [biome-lint, build-database]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
          
      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules/
        
      - name: Build data-source package
        run: npm run build
        working-directory: packages/data-source 

  build-web-tools:
    runs-on: ubuntu-latest
    needs: [biome-lint, build-database]  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
          
      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules/
        
      - name: Build web-tools package
        run: npm run build
        working-directory: packages/web-tools 

  build-test-utils:
    runs-on: ubuntu-latest
    needs: [biome-lint, build-database]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
          
      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules/
        
      - name: Build test-utils package
        run: npm run build
        working-directory: packages/test-utils 