on:
  push:
    branches:
    - main
    paths:
    - apps/server/**
    - packages/**
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: blacksmith-32vcpu-ubuntu-2204
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Setup porter
      uses: porter-dev/setup-porter@v0.1.0
    - name: Deploy stack
      timeout-minutes: 30
      run: exec porter apply 
      env:
        PORTER_CLUSTER: 3155
        PORTER_HOST: https://dashboard.porter.run
        PORTER_PROJECT: 9309
        PORTER_APP_NAME: main-hono-server
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_APP_9309_3155 }}
        PORTER_DEPLOYMENT_TARGET_ID: 7f44813f-4b0c-4be7-add0-94ebb61256bf