name: Deploy Trigger.dev Tasks - Staging

on:
  push:
    branches:
      - mastra-braintrust
    paths:
      - 'trigger/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm ci
        
      - name: 🚀 Deploy to Staging
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
        run: npx trigger.dev@v4-beta deploy --env staging