name: Web Lint

on:
  pull_request:
    paths:
      - "web/**"

jobs:
  web-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./web

      - name: Run linting
        run: pnpm run lint:ci
        working-directory: ./web
